// GET ALL USERS
GET http://localhost:6000/api/users HTTP/1.1

###

// GET USER BY ID
GET http://localhost:6000/api/users/5 HTTP/1.1

###

// POST NEW USER
POST http://localhost:6000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Brandon",
  "bio": "Bio"
}

###

// PUT UPDATE TO USER BY ID
PUT http://localhost:6000/api/users/5 HTTP/1.1
Content-Type: application/json

{
  "name": "Brandon",
  "bio": "..."
}

###

// DELETE USER BY ID
DELETE http://localhost:6000/api/users/5 HTTP/1.1